#!/bin/bash

set -e  # Exit on error

CLAUDE_MD="claude.md"
BACKUP_FILE="claude.md.setup-backup"
LOG_FILE=".setup-execution.log"
INSTRUCTIONS_JSON="/tmp/setup-instructions.json"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

log() {
  echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1" | tee -a "$LOG_FILE"
}

success() {
  echo -e "${GREEN}✓${NC} $1" | tee -a "$LOG_FILE"
}

error() {
  echo -e "${RED}✗${NC} $1" | tee -a "$LOG_FILE"
}

warn() {
  echo -e "${YELLOW}⚠${NC} $1" | tee -a "$LOG_FILE"
}

# Phase 1: Validation
validate_setup() {
  log "Validating setup..."

  if [ ! -f "$CLAUDE_MD" ]; then
    error "claude.md not found in project root"
    exit 1
  fi

  if ! grep -q "Auto-generated by /init:" "$CLAUDE_MD"; then
    error "claude.md is not a setup guide. It appears to be project documentation."
    echo ""
    echo "💡 This command is for initial setup only."
    echo "   Your claude.md has already been set up."
    exit 1
  fi

  success "Validation passed"
}

# Phase 2: Parse instructions
parse_instructions() {
  log "Parsing instructions from claude.md..."

  # Find Node.js parser script
  PARSER_SCRIPT="$HOME/.claude/skills/setup-executor/parse-claude-md.js"

  if [ ! -f "$PARSER_SCRIPT" ]; then
    error "Parser script not found: $PARSER_SCRIPT"
    exit 1
  fi

  # Run parser and save output
  node "$PARSER_SCRIPT" "$CLAUDE_MD" > "$INSTRUCTIONS_JSON" 2>&1

  if [ $? -ne 0 ]; then
    error "Failed to parse claude.md"
    cat "$INSTRUCTIONS_JSON"
    exit 1
  fi

  success "Instructions parsed successfully"
}

# Phase 3: Execute setup tasks
execute_setup() {
  log "Executing setup tasks..."

  # Read framework from parsed data
  FRAMEWORK=$(node -e "console.log(require('$INSTRUCTIONS_JSON').metadata.framework)")

  log "Detected framework: $FRAMEWORK"

  # Execute setup steps
  install_dependencies
  create_folders
  download_fonts
  setup_configs

  success "Setup execution complete"
}

install_dependencies() {
  log "Installing dependencies..."

  # Extract dependencies from JSON
  DEPS=$(node -e "
    const data = require('$INSTRUCTIONS_JSON');
    data.dependencies.forEach(cmd => console.log(cmd));
  ")

  if [ -z "$DEPS" ]; then
    warn "No dependencies to install"
    return
  fi

  echo "$DEPS" | while IFS= read -r cmd; do
    if [ -n "$cmd" ]; then
      log "Running: $cmd"
      eval "$cmd" || error "Failed: $cmd"
    fi
  done

  success "Dependencies installed"
}

create_folders() {
  log "Creating Atomic Design folder structure..."

  # Extract folders from JSON
  FOLDERS=$(node -e "
    const data = require('$INSTRUCTIONS_JSON');
    data.folders.forEach(folder => console.log(folder));
  ")

  echo "$FOLDERS" | while IFS= read -r folder; do
    if [ -n "$folder" ]; then
      mkdir -p "$folder" && success "Created: $folder" || error "Failed: $folder"
    fi
  done

  # Create barrel export files
  create_barrel_exports

  # Install folder documentation
  install_folder_docs

  success "Atomic Design structure created"
}

create_barrel_exports() {
  log "Creating barrel export files..."

  # components/index.ts
  cat > components/index.ts <<'EOF'
// Atomic Design Pattern Exports
export * from './atoms';
export * from './molecules';
export * from './organisms';
export * from './templates';
EOF

  # Empty index.ts for each atomic layer
  for layer in atoms molecules organisms templates; do
    cat > "components/$layer/index.ts" <<EOF
// Export all $layer components here
// Example: export { Button } from './Button';
EOF
  done

  # hooks folder with queries and mutations subfolders
  if [ -d "hooks" ]; then
    mkdir -p hooks/queries hooks/mutations

    # hooks/index.ts
    cat > hooks/index.ts <<'EOF'
export * from './queries';
export * from './mutations';
EOF

    # hooks/queries/index.ts
    cat > hooks/queries/index.ts <<'EOF'
// Export all query hooks here
// Example: export { useUsers } from './useUsers';
EOF

    # hooks/mutations/index.ts
    cat > hooks/mutations/index.ts <<'EOF'
// Export all mutation hooks here
// Example: export { useCreateUser } from './useCreateUser';
EOF
  fi

  # Empty index.ts for other folders
  for folder in utils types schema libs stores constants mock; do
    if [ -d "$folder" ]; then
      cat > "$folder/index.ts" <<EOF
// Export all $folder here
EOF
    fi
  done

  success "Barrel exports created"
}

install_folder_docs() {
  log "Installing folder documentation..."

  FRAMEWORK=$(node -e "console.log(require('$INSTRUCTIONS_JSON').metadata.framework)")
  TEMPLATE_BASE="$HOME/.claude/templates/claude-config/folders"

  # Common folders (hooks, utils, types, schema, libs, stores, constants, mock)
  for folder in hooks utils types schema libs stores constants mock; do
    if [ -d "$folder" ]; then
      cp "$TEMPLATE_BASE/common/$folder.md" "$folder/CLAUDE.md" 2>/dev/null && \
        success "Installed: $folder/CLAUDE.md" || \
        warn "Template not found: common/$folder.md"
    fi
  done

  # hooks subfolders (queries, mutations)
  if [ -d "hooks/queries" ]; then
    cp "$TEMPLATE_BASE/common/hooks-queries.md" "hooks/queries/CLAUDE.md" 2>/dev/null && \
      success "Installed: hooks/queries/CLAUDE.md" || \
      warn "Template not found: common/hooks-queries.md"
  fi

  if [ -d "hooks/mutations" ]; then
    cp "$TEMPLATE_BASE/common/hooks-mutations.md" "hooks/mutations/CLAUDE.md" 2>/dev/null && \
      success "Installed: hooks/mutations/CLAUDE.md" || \
      warn "Template not found: common/hooks-mutations.md"
  fi

  # Framework-specific folders (components layers, styles)
  if [ "$FRAMEWORK" = "expo" ]; then
    [ -d "components/atoms" ] && cp "$TEMPLATE_BASE/expo/components-atoms.md" "components/atoms/CLAUDE.md" && success "Installed: components/atoms/CLAUDE.md"
    [ -d "components/molecules" ] && cp "$TEMPLATE_BASE/expo/components-molecules.md" "components/molecules/CLAUDE.md" && success "Installed: components/molecules/CLAUDE.md"
    [ -d "components/organisms" ] && cp "$TEMPLATE_BASE/expo/components-organisms.md" "components/organisms/CLAUDE.md" && success "Installed: components/organisms/CLAUDE.md"
    [ -d "components/templates" ] && cp "$TEMPLATE_BASE/expo/components-templates.md" "components/templates/CLAUDE.md" && success "Installed: components/templates/CLAUDE.md"
    [ -d "styles" ] && cp "$TEMPLATE_BASE/expo/styles.md" "styles/CLAUDE.md" && success "Installed: styles/CLAUDE.md"
  elif [ "$FRAMEWORK" = "nextjs" ]; then
    [ -d "components/atoms" ] && cp "$TEMPLATE_BASE/next/components-atoms.md" "components/atoms/CLAUDE.md" && success "Installed: components/atoms/CLAUDE.md"
    [ -d "components/molecules" ] && cp "$TEMPLATE_BASE/next/components-molecules.md" "components/molecules/CLAUDE.md" && success "Installed: components/molecules/CLAUDE.md"
    [ -d "components/organisms" ] && cp "$TEMPLATE_BASE/next/components-organisms.md" "components/organisms/CLAUDE.md" && success "Installed: components/organisms/CLAUDE.md"
    [ -d "components/templates" ] && cp "$TEMPLATE_BASE/next/components-templates.md" "components/templates/CLAUDE.md" && success "Installed: components/templates/CLAUDE.md"
    [ -d "styles" ] && cp "$TEMPLATE_BASE/next/styles.md" "styles/CLAUDE.md" && success "Installed: styles/CLAUDE.md"
  fi

  success "Folder documentation installed"
}

download_fonts() {
  log "Downloading Pretendard fonts..."

  # Get font directory from JSON
  FONT_DIR=$(node -e "console.log(require('$INSTRUCTIONS_JSON').metadata.font_dir)")

  mkdir -p "$FONT_DIR"

  # Get fonts from JSON
  FONTS=$(node -e "
    const data = require('$INSTRUCTIONS_JSON');
    data.fonts.forEach(font => console.log(JSON.stringify(font)));
  ")

  echo "$FONTS" | while IFS= read -r font_json; do
    if [ -n "$font_json" ]; then
      NAME=$(echo "$font_json" | node -e "console.log(JSON.parse(require('fs').readFileSync(0, 'utf-8')).name)")
      URL=$(echo "$font_json" | node -e "console.log(JSON.parse(require('fs').readFileSync(0, 'utf-8')).url)")
      OUTPUT="$FONT_DIR/$NAME"

      # Skip if already exists
      if [ -f "$OUTPUT" ]; then
        warn "$NAME already exists (skipping)"
        continue
      fi

      # Download with retry
      RETRY=0
      MAX_RETRIES=3

      while [ $RETRY -lt $MAX_RETRIES ]; do
        if curl -L -o "$OUTPUT" "$URL" 2>/dev/null; then
          SIZE=$(ls -lh "$OUTPUT" | awk '{print $5}')
          success "Downloaded: $NAME ($SIZE)"
          break
        else
          RETRY=$((RETRY + 1))
          if [ $RETRY -lt $MAX_RETRIES ]; then
            warn "Retry $RETRY/$MAX_RETRIES for $NAME"
            sleep 1
          else
            error "Failed to download $NAME after $MAX_RETRIES attempts"
            rm -f "$OUTPUT"
          fi
        fi
      done
    fi
  done

  success "Font download complete"
}

setup_configs() {
  log "Setting up configuration files..."

  # Detect framework
  FRAMEWORK=$(node -e "console.log(require('$INSTRUCTIONS_JSON').metadata.framework)")

  if [ "$FRAMEWORK" = "expo" ]; then
    setup_expo_configs
  elif [ "$FRAMEWORK" = "nextjs" ]; then
    setup_nextjs_configs
  else
    error "Unknown framework: $FRAMEWORK"
    exit 1
  fi

  # Create theme constants (common to both)
  create_theme_constants

  success "Configuration setup complete"
}

setup_expo_configs() {
  log "Setting up Expo + NativeWind configuration..."

  # tailwind.config.js
  cat > tailwind.config.js <<'EOF'
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#007AFF",
        secondary: "#5856D6",
        success: "#34C759",
        warning: "#FF9500",
        danger: "#FF3B30",
      },
      fontFamily: {
        pretendard: ["Pretendard-Regular"],
        "pretendard-medium": ["Pretendard-Medium"],
        "pretendard-semibold": ["Pretendard-SemiBold"],
        "pretendard-bold": ["Pretendard-Bold"],
      },
    },
  },
  plugins: [],
};
EOF
  success "tailwind.config.js created"

  # babel.config.js
  cat > babel.config.js <<'EOF'
module.exports = function (api) {
  api.cache(true);
  return {
    presets: [
      ["babel-preset-expo", { jsxImportSource: "nativewind" }]
    ],
    plugins: [
      "nativewind/babel",
    ],
  };
};
EOF
  success "babel.config.js updated"

  # metro.config.js
  cat > metro.config.js <<'EOF'
const { getDefaultConfig } = require("expo/metro-config");
const { withNativeWind } = require('nativewind/metro');

const config = getDefaultConfig(__dirname);

module.exports = withNativeWind(config, { input: './styles/global.css' });
EOF
  success "metro.config.js created"

  # styles/global.css
  mkdir -p styles
  cat > styles/global.css <<'EOF'
@tailwind base;
@tailwind components;
@tailwind utilities;
EOF
  success "styles/global.css created"

  # styles/index.ts
  cat > styles/index.ts <<'EOF'
// Export global styles
import './global.css';
EOF
  success "styles/index.ts created"
}

setup_nextjs_configs() {
  log "Setting up Next.js + Tailwind CSS configuration..."

  # tailwind.config.ts
  cat > tailwind.config.ts <<'EOF'
import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#007AFF",
        secondary: "#5856D6",
        success: "#34C759",
        warning: "#FF9500",
        danger: "#FF3B30",
      },
      fontFamily: {
        pretendard: ["var(--font-pretendard)"],
        "pretendard-medium": ["var(--font-pretendard-medium)"],
        "pretendard-semibold": ["var(--font-pretendard-semibold)"],
        "pretendard-bold": ["var(--font-pretendard-bold)"],
      },
    },
  },
  plugins: [],
};

export default config;
EOF
  success "tailwind.config.ts created"

  # postcss.config.mjs
  cat > postcss.config.mjs <<'EOF'
/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};

export default config;
EOF
  success "postcss.config.mjs created"

  # styles/globals.css
  mkdir -p styles
  cat > styles/globals.css <<'EOF'
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --font-pretendard: "Pretendard", sans-serif;
    --font-pretendard-medium: "Pretendard Medium", sans-serif;
    --font-pretendard-semibold: "Pretendard SemiBold", sans-serif;
    --font-pretendard-bold: "Pretendard Bold", sans-serif;
  }
}
EOF
  success "styles/globals.css created"

  # styles/index.ts
  cat > styles/index.ts <<'EOF'
// Export global styles
export {};
EOF
  success "styles/index.ts created"
}

create_theme_constants() {
  log "Creating theme constants..."

  mkdir -p constants

  cat > constants/theme.ts <<'EOF'
export const colors = {
  primary: "#007AFF",
  secondary: "#5856D6",
  success: "#34C759",
  warning: "#FF9500",
  danger: "#FF3B30",
  background: "#FFFFFF",
  text: "#000000",
  textSecondary: "#8E8E93",
} as const;

export const spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
} as const;

export const borderRadius = {
  sm: 4,
  md: 8,
  lg: 12,
  xl: 16,
  full: 9999,
} as const;

export const fontSize = {
  xs: 12,
  sm: 14,
  base: 16,
  lg: 18,
  xl: 20,
  "2xl": 24,
  "3xl": 30,
} as const;
EOF

  success "constants/theme.ts created"

  # constants/index.ts
  cat > constants/index.ts <<'EOF'
export * from './theme';
EOF

  success "constants/index.ts created"
}

# Phase 4: Finalize
finalize_setup() {
  log "Finalizing setup..."

  # Backup original claude.md
  cp "$CLAUDE_MD" "$BACKUP_FILE"
  success "Backed up claude.md → $BACKUP_FILE"

  # Install final project documentation
  FRAMEWORK=$(node -e "console.log(require('$INSTRUCTIONS_JSON').metadata.framework)")
  TEMPLATE_BASE="$HOME/.claude/templates/claude-config"

  if [ "$FRAMEWORK" = "expo" ]; then
    cp "$TEMPLATE_BASE/expo.md" "$CLAUDE_MD"
    success "Installed Expo project documentation → claude.md"
  elif [ "$FRAMEWORK" = "nextjs" ]; then
    cp "$TEMPLATE_BASE/next.md" "$CLAUDE_MD"
    success "Installed Next.js project documentation → claude.md"
  else
    error "Unknown framework: $FRAMEWORK"
  fi

  log "Setup finalization complete"
}

# Main execution
main() {
  echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e "${CYAN}🚀 Setup Executor${NC}"
  echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo ""

  # Clear or create log file
  > "$LOG_FILE"

  validate_setup
  parse_instructions
  execute_setup
  finalize_setup

  echo ""
  echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e "${GREEN}✅ Setup Complete!${NC}"
  echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo ""
  echo -e "${YELLOW}📄 Original setup guide backed up:${NC} $BACKUP_FILE"
  echo -e "${YELLOW}📝 Execution log:${NC} $LOG_FILE"
  echo ""
}

main "$@"
